"use client"

import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { 
  TrendingUp,
  Shield,
  Crown,
  Star,
  Coins,
  Users,
  MessageSquare,
  Video,
  CheckCircle,
  ArrowRight,
  AlertTriangle,
  FileText,
  Zap
} from 'lucide-react'

export function InvestorTiers() {
  console.log('InvestorTiers component rendered')

  const investorTiers = [
    {
      name: 'Bronze Stake',
      price: '$2,500',
      equity: '0.05%',
      description: 'Founding Access Tier',
      color: 'cosmic-cyan',
      features: [
        'Receive official Bronze NFT investor badge',
        'Access to exclusive early-stage updates',
        'Tier-based content access (Q4 2024)',
        'Private investor Discord access',
        'Revenue-share eligibility (0.1%)',
        'Community voting rights on select features'
      ],
      icon: Shield,
      popular: false,
      tagline: 'Your early belief means everything. Welcome to the start of something massive.'
    },
    {
      name: 'Silver Stake',
      price: '$5,000',
      equity: '0.10%',
      description: 'Enhanced Access Tier',
      color: 'cosmic-purple',
      features: [
        '0.5% lifetime revenue share',
        'Early feature access & influence',
        'NFT badge with Silver-tier perks',
        'Exclusive Discord role + sneak previews',
        'Priority creator onboarding & support'
      ],
      icon: Crown,
      popular: true
    },
    {
      name: 'Gold Stake',
      price: '$10,000',
      equity: '0.25%',
      description: 'Split Payment Option Available',
      color: 'cosmic-amber',
      features: [
        'NFT Badge: Gold Elite Investor',
        '0.25% Class B equity (non-controlling)',
        'All Silver tier benefits',
        'Feature voting rights (non-binding)',
        'Private AMA sessions with founders',
        'Advisory role in platform development'
      ],
      icon: Star,
      popular: false,
      splitPayment: true
    }
  ]

  const legalPoints = [
    {
      icon: AlertTriangle,
      title: 'No Control or Voting Rights',
      description: 'Class B equity shares are non-controlling and do not grant voting rights, board seats, or operational authority. Investors receive pro-rata revenue share based on total company income post-cash-flow breakeven.'
    },
    {
      icon: Shield,
      title: 'Platform Ownership Clause',
      description: 'All content created using the Nemurium platform is legally owned by Nemurium. Creators may be monetized based on engagement or resale'
    },
    {
      icon: TrendingUp,
      title: 'Revenue Share Conditions',
      description: 'Revenue sharing is based on gross revenue generated by Nemurium\'s official products and only begins after cash-positive monetization'
    },
    {
      icon: FileText,
      title: 'NFT Badge Symbolism',
      description: 'NFTs issued to investors are symbolic and do not confer any legal, financial, or ownership rights. They serve as tier identifiers'
    },
    {
      icon: Coins,
      title: 'Risk Acknowledgment',
      description: 'By participating, you acknowledge that Nemurium is in early development and outcomes are not guaranteed. Refunds will not be issued'
    },
    {
      icon: Star,
      title: 'Right to Modify',
      description: 'Nemurium may adjust, restructure, or eliminate tier benefits, revenue models, or distribution mechanisms during formal incorporation'
    }
  ]

  return (
    <div className="py-20 px-6 bg-gradient-to-b from-transparent via-cosmic-amber/5 to-transparent">
      <div className="container mx-auto max-w-6xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <Badge className="bg-cosmic-gradient text-white font-bold px-4 py-2 mb-6">
            <Coins className="w-4 h-4 mr-2" />
            Limited Opportunity
          </Badge>
          
          <h2 className="text-4xl md:text-6xl font-black text-cosmic-white mb-6">
            <span className="text-gradient">Founding Equity</span> Investment
          </h2>
          
          <div className="bg-cosmic-purple/20 border border-cosmic-purple/30 rounded-lg p-6 max-w-4xl mx-auto mb-8">
            <p className="text-xl text-cosmic-white font-medium mb-2">
              <strong>Founding Equity Investment:</strong> Receive Class B shares (non-controlling equity) in Nemurium, with shared revenue but no voting or managerial power.
            </p>
            <p className="text-lg text-cosmic-white/80">
              Our tiered equity model helps you participate in building the operating system of the immersive internet.
            </p>
          </div>
          
          <div className="bg-cosmic-amber/20 border border-cosmic-amber/30 rounded-lg p-6 max-w-3xl mx-auto">
            <p className="text-lg text-cosmic-white font-medium mb-2">
              🎯 <strong>Investment Goal:</strong> Raise $200K-$250K for 10-15% total equity
            </p>
            <p className="text-cosmic-white/80">
              Each investor receives: Class B equity shares, unique NFT badge, pro-rata revenue share, and tier-specific platform access and influence.
            </p>
          </div>
        </motion.div>

        {/* Legal Disclaimer Section */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <Card className="glass-panel border-cosmic-amber/30 p-8 bg-cosmic-amber/5">
            <div className="text-center mb-8">
              <AlertTriangle className="w-12 h-12 text-cosmic-amber mx-auto mb-4" />
              <h3 className="text-2xl font-bold text-cosmic-white mb-4">Equity Investment Disclosure</h3>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6">
              {legalPoints.map((point, index) => {
                const Icon = point.icon
                return (
                  <motion.div
                    key={point.title}
                    initial={{ opacity: 0, scale: 0.9 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    className="flex items-start gap-4"
                  >
                    <Icon className="w-6 h-6 text-cosmic-amber flex-shrink-0 mt-1" />
                    <div>
                      <h4 className="text-lg font-bold text-cosmic-white mb-2">{point.title}</h4>
                      <p className="text-cosmic-white/70 text-sm">{point.description}</p>
                    </div>
                  </motion.div>
                )
              })}
            </div>
            
            <div className="text-center mt-8 pt-6 border-t border-cosmic-amber/20">
              <h4 className="text-lg font-bold text-cosmic-white mb-4">Nemurium Investor Risk Disclosure</h4>
              <div className="text-cosmic-white/70 text-sm space-y-3 max-w-4xl mx-auto">
                <p className="font-medium text-cosmic-amber">
                  Nemurium is a pre-revenue, early-stage immersive technology platform. Participation in any contribution or investor tier is voluntary and involves substantial risk.
                </p>
                <p>
                  <strong>Platform Ownership:</strong> All content created using the Nemurium platform is legally owned by Nemurium. Creators may be monetized based on engagement or resale, but Nemurium reserves the right to use, modify, distribute, or repurpose any content created using its tools.
                </p>
                <p>
                  <strong>Investment Terms:</strong> These are Class B shares with no voting rights, board seats, or operational control. Revenue share is paid quarterly if applicable, contingent on platform monetization. NFT badges are symbolic tier identifiers only.
                </p>
                <p className="italic text-cosmic-white/60">
                  By participating, you acknowledge this is high-risk support of a visionary project. Refunds will not be issued. Nemurium may adjust benefits during formal incorporation or funding transitions.
                </p>
                <p className="text-xs text-cosmic-white/50">
                  For questions, email support@nemurium.com
                </p>
              </div>
            </div>
          </Card>
        </motion.div>

        {/* Investor Tiers */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <div className="grid lg:grid-cols-3 gap-8">
            {investorTiers.map((tier, index) => {
              const Icon = tier.icon
              return (
                <motion.div
                  key={tier.name}
                  initial={{ opacity: 0, y: 30, scale: 0.9 }}
                  whileInView={{ opacity: 1, y: 0, scale: 1 }}
                  transition={{ duration: 0.6, delay: index * 0.2 }}
                  viewport={{ once: true }}
                  className="relative"
                >
                  {tier.popular && (
                    <Badge className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-cosmic-gradient text-white font-bold px-4 py-1 z-10">
                      Most Strategic
                    </Badge>
                  )}
                  
                  <Card className={`glass-panel border-white/10 p-8 h-full floating-card ${
                    tier.popular ? 'ring-2 ring-cosmic-purple/50 cosmic-glow' : ''
                  }`}>
                    <div className="text-center mb-8">
                      <Icon className={`w-16 h-16 mx-auto mb-6 ${
                        tier.color === 'cosmic-purple' ? 'text-cosmic-purple' :
                        tier.color === 'cosmic-cyan' ? 'text-cosmic-cyan' :
                        'text-cosmic-amber'
                      }`} />
                      
                      <h3 className="text-2xl font-black text-cosmic-white mb-2">{tier.name}</h3>
                      <p className="text-cosmic-white/70 mb-4">{tier.description}</p>
                      
                      <div className="mb-4">
                        <div className="text-4xl font-black text-gradient mb-2">{tier.price}</div>
                        <Badge className={`${
                          tier.color === 'cosmic-purple' ? 'bg-cosmic-purple/20 text-cosmic-purple' :
                          tier.color === 'cosmic-cyan' ? 'bg-cosmic-cyan/20 text-cosmic-cyan' :
                          'bg-cosmic-amber/20 text-cosmic-amber'
                        } font-bold`}>
                          {tier.equity} Equity Share
                        </Badge>
                      </div>
                    </div>

                    <div className="space-y-4 mb-8">
                      {tier.features.map((feature, idx) => (
                        <div key={idx} className="flex items-start gap-3">
                          <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
                          <span className="text-cosmic-white/80 text-sm leading-relaxed">{feature}</span>
                        </div>
                      ))}
                      
                      {tier.tagline && (
                        <div className="mt-6 p-4 bg-cosmic-cyan/10 border border-cosmic-cyan/20 rounded-lg">
                          <p className="text-cosmic-cyan font-medium italic text-sm">{tier.tagline}</p>
                        </div>
                      )}
                    </div>

                    <div className="space-y-3">
                      {tier.splitPayment ? (
                        // Gold Stake Split Payment Buttons
                        <>
                          <div className="text-center mb-4">
                            <h4 className="text-lg font-bold text-cosmic-amber mb-2">Split Payment Option</h4>
                            <p className="text-cosmic-white/70 text-sm mb-4">Secure your Gold Stake with flexible payment options</p>
                          </div>
                          
                          <Button 
                            onClick={() => window.open('https://jaytee5644.gumroad.com/l/howc1', '_blank')}
                            className="w-full font-bold bg-cosmic-amber/20 border-cosmic-amber/50 text-cosmic-amber hover:bg-cosmic-amber/30"
                            variant="outline"
                            size="lg"
                          >
                            <Coins className="w-4 h-4 mr-2" />
                            Part 1: Reserve ($5,000)
                            <ArrowRight className="w-4 h-4 ml-2" />
                          </Button>
                          
                          <Button 
                            onClick={() => window.open('https://jaytee5644.gumroad.com/l/tzholi', '_blank')}
                            className="w-full font-bold bg-cosmic-amber/20 border-cosmic-amber/50 text-cosmic-amber hover:bg-cosmic-amber/30"
                            variant="outline"
                            size="lg"
                          >
                            <Star className="w-4 h-4 mr-2" />
                            Part 2: Complete ($5,000)
                            <ArrowRight className="w-4 h-4 ml-2" />
                          </Button>
                          
                          <div className="bg-red-500/20 border border-red-500/30 rounded-lg p-3 mt-4">
                            <p className="text-red-400 text-xs">
                              ⚠️ <strong>Important:</strong> Part 1 holds your access for 30 days. Complete Part 2 within 30 days to retain Gold Tier benefits. 
                              If not completed, you will be moved to Silver Stake ($5,000) tier. No refunds for missed completion windows.
                            </p>
                          </div>
                        </>
                      ) : (
                        // Regular Single Payment Button
                        <Button 
                          onClick={() => {
                            const investmentUrls = {
                              'Bronze Stake': 'https://jaytee5644.gumroad.com/l/ntpmhch',
                              'Silver Stake': 'https://jaytee5644.gumroad.com/l/nfuxvi',
                              'Gold Stake': 'https://jaytee5644.gumroad.com/l/howci'
                            }
                            window.open(investmentUrls[tier.name as keyof typeof investmentUrls], '_blank')
                          }}
                          className={`w-full font-bold ${
                            tier.popular 
                              ? 'btn-cosmic text-white' 
                              : 'border-white/20 text-cosmic-white hover:bg-white/5'
                          }`}
                          variant={tier.popular ? 'default' : 'outline'}
                          size="lg"
                        >
                          <Coins className="w-4 h-4 mr-2" />
                          Invest {tier.price}
                          <ArrowRight className="w-4 h-4 ml-2" />
                        </Button>
                      )}
                      
                      <Button 
                        onClick={() => {
                          const pdfUrls = {
                            'Bronze Stake': '/pdfs/Nemurium_Bronze_Tier_Agreement.pdf',
                            'Silver Stake': '/pdfs/Nemurium_Silver_Tier_Agreement.pdf',
                            'Gold Stake': '/pdfs/Nemurium_Gold_Tier_Agreement.pdf'
                          }
                          window.open(pdfUrls[tier.name as keyof typeof pdfUrls], '_blank')
                        }}
                        variant="ghost"
                        size="sm"
                        className="w-full text-cosmic-white/60 hover:text-cosmic-white hover:bg-cosmic-white/10"
                      >
                        <FileText className="w-4 h-4 mr-2" />
                        View Agreement PDF
                      </Button>
                    </div>
                  </Card>
                </motion.div>
              )
            })}
          </div>
        </motion.div>

        {/* NFT Badge Preview */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h3 className="text-3xl font-black text-cosmic-white mb-8">
            Exclusive <span className="text-gradient">NFT Badges</span>
          </h3>
          
          <div className="grid md:grid-cols-3 gap-6">
            {investorTiers.map((tier, index) => (
              <motion.div
                key={tier.name}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <Card className="glass-panel border-white/10 p-6">
                  <div className={`w-24 h-24 mx-auto mb-4 rounded-full ${
                    tier.color === 'cosmic-purple' ? 'bg-cosmic-purple/20 border-2 border-cosmic-purple/30' :
                    tier.color === 'cosmic-cyan' ? 'bg-cosmic-cyan/20 border-2 border-cosmic-cyan/30' :
                    'bg-cosmic-amber/20 border-2 border-cosmic-amber/30'
                  } flex items-center justify-center`}>
                    <Zap className={`w-10 h-10 ${
                      tier.color === 'cosmic-purple' ? 'text-cosmic-purple' :
                      tier.color === 'cosmic-cyan' ? 'text-cosmic-cyan' :
                      'text-cosmic-amber'
                    }`} />
                  </div>
                  <h4 className="text-lg font-bold text-cosmic-white mb-2">{tier.name}</h4>
                  <p className="text-cosmic-white/70 text-sm">Exclusive digital badge proving your founding investor status</p>
                </Card>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Call to Action */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <Card className="glass-panel border-cosmic-gradient p-8 cosmic-glow">
            <h3 className="text-3xl font-black text-cosmic-white mb-4">
              Ready to Shape the <span className="text-gradient">Immersive Future?</span>
            </h3>
            <p className="text-lg text-cosmic-white/80 mb-8 max-w-2xl mx-auto">
              Join a select group of visionaries who believe in the next evolution of digital creativity. 
              Your investment helps build the infrastructure for the spatial internet.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                onClick={() => {
                  const investorSection = document.getElementById('founding-investor')
                  if (investorSection) {
                    investorSection.scrollIntoView({ behavior: 'smooth' })
                  }
                }}
                size="lg"
                className="btn-cosmic text-white font-bold px-8"
              >
                <Star className="w-5 h-5 mr-2" />
                Submit Investment Interest
              </Button>
              
              <Button 
                onClick={() => {
                  const waitlistSection = document.getElementById('waitlist')
                  if (waitlistSection) {
                    waitlistSection.scrollIntoView({ behavior: 'smooth' })
                  }
                }}
                variant="outline"
                size="lg"
                className="border-cosmic-cyan/50 text-cosmic-cyan hover:bg-cosmic-cyan/10"
              >
                <Users className="w-5 h-5 mr-2" />
                Join Free Waitlist Instead
              </Button>
            </div>
          </Card>
        </motion.div>

        {/* Dashboard Status Update */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 1.0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <Card className="glass-panel border-cosmic-cyan/30 p-8 bg-cosmic-cyan/5">
            <div className="text-center mb-6">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-cosmic-cyan/20 border-2 border-cosmic-cyan/30 flex items-center justify-center">
                <TrendingUp className="w-8 h-8 text-cosmic-cyan" />
              </div>
              <h3 className="text-2xl font-bold text-cosmic-white mb-4">Dashboard Launch Status</h3>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto">
              <div className="text-left">
                <h4 className="text-lg font-bold text-cosmic-cyan mb-3">📊 Phase 1: Preview Live ✅</h4>
                <ul className="text-cosmic-white/80 text-sm space-y-2">
                  <li>• Basic dashboard preview available</li>
                  <li>• Investor tier information display</li>
                  <li>• Platform metrics overview</li>
                  <li>• Feature roadmap visibility</li>
                </ul>
              </div>
              
              <div className="text-left">
                <h4 className="text-lg font-bold text-cosmic-amber mb-3">🔐 Phase 2: Full Launch (Q4 2025)</h4>
                <ul className="text-cosmic-white/80 text-sm space-y-2">
                  <li>• Secure login with OAuth/Wallet</li>
                  <li>• Real-time platform metrics</li>
                  <li>• Tier-based content access</li>
                  <li>• Revenue tracking & payouts</li>
                </ul>
                <div className="mt-4 flex flex-col gap-2">
                  <Button
                    onClick={() =>
                      window.open("/pdfs/Nemurium-TierB-Agreement.pdf", "_blank")
                    }
                    className="w-full"
                  >
                    View Agreement PDF
                  </Button>
                  <Button
                    onClick={() =>
                      window.open("https://jaytee5644.gumroad.com/l/ihxcli", "_blank")
                    }
                    className="w-full"
                  >
                    Invest Now
                  </Button>
                </div>
              </div>
            </div>
            
            <div className="mt-8 pt-6 border-t border-cosmic-cyan/20">
              <p className="text-cosmic-white/70 text-sm max-w-3xl mx-auto">
                The investor dashboard is actively being developed. Phase 1 provides essential preview features, 
                while Phase 2 will deliver the complete secure investor experience with full authentication, 
                real-time metrics, and automated tier recognition.
              </p>
            </div>
          </Card>
        </motion.div>
      </div>
    </div>
  )
}